services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - nginx_data:/usr/share/nginx/html # 为网站内容设置卷
      - nginx_config:/etc/nginx # 为Nginx配置文件设置卷
      - nginx-logs:/var/log/nginx
    restart: unless-stopped # 出现错误时重启Nginx容器

volumes:
  nginx_data:
    driver: local
  nginx_config:
    driver: local
  nginx-logs:
    driver: local
