version: '3.8'
services:
  redis:
    image: redis
    container_name: docker_redis
    command: redis-server /etc/redis/redis.conf --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - "./redis.conf:/etc/redis/redis.conf"
      - "redis-data:/data"
volumes:
  redis-data:
    driver: local