services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "9638:9638"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge