[common]
server_addr = "47.106.99.224"
server_port = 9300
token = "oR$x83Y#q"

[proxy_nginx]
type = "tcp"
local_ip = "nginx"
local_port = 10000
remote_port = 10000

[proxy_gitlab]
type = "tcp"
local_ip = "gitlab"
local_port = 22
remote_port = 10022
